// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ErrorDialog(arg1) {
  return window['go']['main']['App']['ErrorDialog'](arg1);
}

export function InfoDialog(arg1) {
  return window['go']['main']['App']['InfoDialog'](arg1);
}

export function WarningDialog(arg1, arg2) {
  return window['go']['main']['App']['WarningDialog'](arg1, arg2);
}
