// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ErrorDialog(arg1:string):Promise<void>;

export function InfoDialog(arg1:string):Promise<void>;

export function WarningDialog(arg1:string,arg2:string):Promise<boolean>;
